### PR TITLE
Reduce memory

### PR DESCRIPTION
**Pull request by imbsky**
This PR reduces memory. If you want to know more about the work I have done in this PR, I recommend that you access the following links. and I'm not familiar with Heroku at all. So I'm not surprised if something goes wrong. All reviews are welcome!

- [Taming Rails memory bloat](https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat)
- [Malloc Can Double Multi-threaded Ruby Program Memory Usage](https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html)

### CODE REVIEW

**Comment by imbsky** [comment]
See also: [Feature #14718: Use jemalloc by default? - Ruby master - Ruby Issue Tracking System](https://bugs.ruby-lang.org/issues/14718)

**Comment by imbsky** [comment]
I just updated a Japanese article. If you prefer Japanese article, I would like to have you read this.

[Rubyのメモリ使用量を減らす](https://qiita.com/imbsky/items/fca64e52f6e1d03504c9)

**Comment by imbsky** [comment]
Oh I found more detailed Japanese article.

[mallocでマルチスレッドプログラムのメモリが倍増する理由](https://techracho.bpsinc.jp/hachi8833/2017_12_28/50109)

**Comment by imbsky** [comment]
@yamashush friendly ping

**Comment by imbsky** [comment]
Can you please either merge or close this? If you can't, others who like this change can decide to maintain it by themselves or abandon.

**Comment by yamashush** [comment]
Thank you for your PR and sorry to reply so late.
I'll try it.

**Comment by imbsky** [comment]
No worries.

**Pull request merged**
